### ISSUE TITLE
Theano doesn't work

### ISSUE THREAD

**Issue by variac** [startupml/jetpack#22]
When I start the container in a non-detached mode, I get the following after a brand new, clean install on Ubuntu 14.04 LTS.

Traceback (most recent call last):
  File "/opt/miniconda/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/core/application.py", line 369, in initialize
    self.parse_command_line(argv)
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/config/application.py", line 471, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/config/application.py", line 402, in initialize_subcommand
    subapp = import_item(subapp)
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 64, in <module>
    from .services.contents.manager import ContentsManager
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/html/services/contents/manager.py", line 16, in <module>
    from IPython.nbformat import sign, validate, ValidationError
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/nbformat/__init__.py", line 29, in <module>
    from .validator import validate, ValidationError
  File "/opt/miniconda/lib/python2.7/site-packages/IPython/nbformat/validator.py", line 21, in <module>
    raise ImportError(str(e) + verbose_msg)
ImportError: No module named jsonschema

    IPython notebook format depends on the jsonschema package:
    
        https://pypi.python.org/pypi/jsonschema
    
    Please install it first.

**Comment by gwulfs** [comment]
change this line - https://github.com/startupml/jetpack/blob/master/theano/Dockerfile#L21

from - pip install ipython

to - pip install "ipython[notebook]"
